import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowUpRight, SlidersHorizontal } from "lucide-react";
import { useMemo, useState } from "react";
import { properties } from "@/lib/properties";
import { Button } from "@/components/ui/button";
import { Reveal } from "@/components/reveal";

export const Route = createFileRoute("/properties")({ head: () => ({ meta: [{ title: "Properties — Ali Properties Lahore" }, { name: "description", content: "Explore curated residential, commercial and plot opportunities across Lahore." }, { property: "og:title", content: "Curated Lahore Properties — Ali Properties" }, { property: "og:description", content: "A considered collection of Lahore property opportunities." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: PropertiesPage });

function PropertiesPage() {
  const [type, setType] = useState("All"); const [location, setLocation] = useState("All"); const [budget, setBudget] = useState("All");
  const filtered = useMemo(() => properties.filter((p) => (type === "All" || p.type === type) && (location === "All" || p.location === location) && (budget === "All" || (budget === "Under 10 Cr" ? p.priceValue < 10 : p.priceValue >= 10))), [type, location, budget]);
  return <div className="min-h-screen bg-ink px-5 pb-28 pt-36 sm:px-8 lg:px-12"><div className="mx-auto max-w-[1500px]"><p className="editorial-label text-primary">The portfolio</p><h1 className="mt-5 text-6xl text-cream sm:text-8xl lg:text-9xl">Properties</h1><div className="mt-12 grid gap-5 border-y border-border py-5 sm:grid-cols-3"><Filter label="Type" value={type} setValue={setType} options={["All","Residential","Commercial","Plots"]} /><Filter label="Location" value={location} setValue={setLocation} options={["All", ...Array.from(new Set(properties.map((p) => p.location)))]} /><Filter label="Price" value={budget} setValue={setBudget} options={["All","Under 10 Cr","10 Cr+"]} /></div><div className="mt-16 grid items-start gap-x-8 gap-y-16 md:grid-cols-2 lg:grid-cols-12">{filtered.map((property,index) => <Reveal key={property.id} className={`${index % 3 === 0 ? "lg:col-span-7" : "lg:col-span-5"} group`}><Link to="/properties/$id" params={{ id: property.id }}><div className={`${index % 3 === 0 ? "aspect-[6/5]" : "aspect-[4/5]"} overflow-hidden`}><img src={property.image} alt={property.title} loading="lazy" width={1400} height={1600} className="h-full w-full image-wash object-cover transition-transform duration-700 group-hover:scale-105" /></div><div className="relative mt-5 flex justify-between border-t border-border pt-4 after:absolute after:left-0 after:top-[-1px] after:h-px after:w-full after:origin-left after:scale-x-0 after:bg-primary after:transition-transform group-hover:after:scale-x-100"><div><p className="editorial-label text-primary">{property.type} · {property.location}</p><h2 className="mt-2 text-3xl text-cream sm:text-4xl">{property.title}</h2><p className="mt-2 text-xs text-muted-foreground">{property.size} · {property.bedrooms}</p></div><div className="text-right"><p className="text-sm text-cream">{property.price}</p><ArrowUpRight className="ml-auto mt-3 size-4 text-primary" /></div></div></Link></Reveal>)}</div>{filtered.length === 0 && <p className="py-24 text-center text-muted-foreground">No properties match these filters.</p>}</div></div>;
}
function Filter({ label, value, setValue, options }: { label: string; value: string; setValue: (value: string) => void; options: string[] }) { return <label className="grid grid-cols-[auto_1fr] items-center gap-3"><SlidersHorizontal className="size-4 text-primary" /><span className="sr-only">{label}</span><select className="w-full bg-transparent py-2 text-sm text-cream outline-none" value={value} onChange={(e) => setValue(e.target.value)}>{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }